# permissions for end users to view restcalls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: restcall-operator
    app.kubernetes.io/managed-by: kustomize
  name: restcall-viewer-role
rules:
- apiGroups:
  - call.restcall
  resources:
  - restcalls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - call.restcall
  resources:
  - restcalls/status
  verbs:
  - get
